### ISSUE TITLE
Can't request tokenAuth Mutation

### ISSUE THREAD

**Issue by oc7o** [nrbnlulu/strawberry-django-auth#55]
# Prerequisites

* [x] Is it a bug?
* [ ] Is it a new feature?
* [ ] Is it a question?
* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [x] Did you perform a cursory search?

# Description

I try to login using the tokenAuth Mutation, but when I this, I get:
{
  "data": null,
  "errors": [
    {
      "message": "'StrawberryField' object has no attribute 'get_result'",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ]
}

# Steps to Reproduce

1. [Clone this repo]
`git clone https://github.com/nrbnlulu/strawberry-django-auth.git`
and `cd quickstart`

2. [Install requirements.txt]
`pip install -r requirements.txt`

requirements (btw. I am using an anaconda3 env):
anyio==3.6.1
appdirs==1.4.4
asgiref==3.5.2
attrs @ file://[...]
backports.cached-property==1.0.2
black==19.10b0
certifi @ file://[...]
click==8.1.3
Django==4.0.6
django-admin-display==1.3.0
django-cors-headers==3.13.0
django-filter==22.1
django-mathfilters==1.0.0
graphql-core==3.2.1
h11==0.13.0
idna==3.3
mypy-extensions==0.4.3
packaging==21.3
pathspec==0.7.0
Pillow==9.2.0
psutil==5.9.1
Pygments==2.12.0
PyJWT==2.4.0
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.5
regex @ file://[...]
six==1.16.0
sniffio==1.2.0
sqlparse==0.4.2
starlette==0.20.4
strawberry-django-auth==0.3.3.2
strawberry-django-jwt==0.2.2
strawberry-graphql==0.121.0
strawberry-graphql-django==0.4.0
toml @ file://[...]
typed-ast @ file://[...]
typing_extensions==4.3.0
uvicorn==0.18.2

3. [Migrating and creating superuser]
`python manage.py migrate`
`python manage.py createsuperuser`

4. [Running server and requesting]

`python manage.py runserver`

Go to http://localhost:8000/graphql

Sending: (https://nrbnlulu.github.io/strawberry-django-auth/quickstart/#login)

mutation {
    tokenAuth(username: "oc7o", password: "1234Password") {
    	success
        errors
        obtainPayload {
          token
          refreshToken
          refreshExpiresIn
          payload {
              exp
              origIat
              username
          }
        }
    }
}

## Expected behavior

Getting something like that... (https://nrbnlulu.github.io/strawberry-django-auth/quickstart/#login)
{
  "data": {
    "tokenAuth": {
      "success": true,
      "errors": null,
      "obtainPayload": {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTM2MDkxOTQsIm9yaWdJYXQiOjE2NTM2MDg4OTQsInVzZXJuYW1lIjoibmV3X3VzZXIxIn0.FxXaWKToi5mTzPcKAz16K2GWnIvsTBKio_BEyCdF5fs",
        "refreshToken": "e7a784476810f880eb93f3827cd881d834235598",
        "refreshExpiresIn": 1654213694,
        "payload": {
          "exp": 1653609194,
          "origIat": 1653608894,
          "username": "oc7o"
        }
      }
    }
  }
}

## Actual behavior

Console Output:

'StrawberryField' object has no attribute 'get_result'

GraphQL request:2:5
1 | mutation {
2 |     tokenAuth(username: "oc7o", password: "1234Password") {
  |     ^
3 |     	errors
Traceback (most recent call last):
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/strawberry_django_jwt/middleware.py", line 129, in resolve
    return await result
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 501, in _async_resolver
    return await await_maybe(_get_result(_source, strawberry_info, **kwargs))
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/strawberry/utils/await_maybe.py", line 12, in await_maybe
    return await value
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/gqlauth/bases/mixins.py", line 261, in afield
    return await sync_to_async(cls.resolve_mutation)(info, **kwargs)
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/gqlauth/user/resolvers.py", line 461, in resolve_mutation
    res = cls.obtain.get_result(None, None, [cls, info], query_input_)
AttributeError: 'StrawberryField' object has no attribute 'get_result'
Stack (most recent call last):
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/strawberry/django/views.py", line 257, in dispatch
    result = await self.schema.execute(
  File "[...]/opt/anaconda3/envs/oi/lib/python3.10/site-packages/strawberry/schema/schema.py", line 206, in execute
    self.process_errors(result.errors, execution_context=execution_context)

# Requirements

See above

If you need more infos, pls say.

🐙 oc7o

**Comment by nrbnlulu** [comment]
Hey!

Update strawberry :smile: [ Its a known issue ](https://github.com/strawberry-graphql/strawberry/pull/2038)

**Comment by oc7o** [comment]
Oh... sometimes anaconda is weird 🧐
Thank you for your help!
😁
