### ISSUE TITLE
Issue in using email or both username and email for log in

### ISSUE THREAD

**Issue by jbdura** [nrbnlulu/strawberry-django-auth#561]
# Prerequisites
*Feel free to just say what you want and remove this template.*

* [x] Is it a bug?
* [ ] Is it a new feature?
* [x] Is it a question?
* [ ] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description
tokenAuth mutation works fine when I use username. When I change the option to email, the package fails

Description of the bug/feature/question

# Steps to Reproduce

If we need to reproduce and you don't provide steps for it, it will be closed. Alternatively, you can link a repo with the code to run your issue.

1. [First Step]
```
from gqlauth.settings_type import GqlAuthSettings, email_field, username_field

AUTH_USER_MODEL = 'users.CustomUser'


GQL_AUTH = GqlAuthSettings(
    LOGIN_FIELDS={email_field}, -> when I enable this, it throws an error , see below
    # LOGIN_FIELDS = {username_field}, -> when I uncomment this line, it works fine

)
```
2. [Second Step]
![Screenshot from 2024-07-08 09-55-23](https://github.com/nrbnlulu/strawberry-django-auth/assets/99818207/98263d78-6cea-44f9-a78b-920f730b6d46)

4. [and so on...]

## Expected behavior

What you expected to happen

## Actual behavior

What actually happened

# Requirements

Paste the packages you are using, you can get this information from executing `pip freeze`.

graphql-core              3.2.3
graphql-relay             3.2.0
django-cors-headers       4.3.1
django-environ            0.11.2
django-filter             23.5
django-ratelimit          4.1.0
django-stubs              4.2.7
django-stubs-ext          5.0.2
strawberry-django-auth    0.376.11
strawberry-graphql        0.235.0
strawberry-graphql-django 0.44.2

**Comment by nrbnlulu** [comment]
can you provide a traceback?

**Comment by jbdura** [comment]
$ py manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 08, 2024 - 08:52:09
Django version 5.0.6, using settings 'AgriSocial.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[08/Jul/2024 08:52:12] "GET /users/graphql/ HTTP/1.1" 200 4359
[08/Jul/2024 08:52:16] "POST /users/graphql/ HTTP/1.1" 200 47820
'ObtainJSONWebTokenInput' object has no attribute 'username'

GraphQL request:2:3
1 | mutation {
2 |   tokenAuth(email: "user1@example.com", password: "SuperSecureP@sw0rd") {
  |   ^
3 |     success
Traceback (most recent call last):
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/graphql/execution/execute.py", line 528, in await_result
    return_type, field_nodes, info, path, await result
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/strawberry_django/fields/field.py", line 223, in async_resolver
    resolved = await result  # type: ignore
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/strawberry_django/resolvers.py", line 105, in async_resolver
    return sync_resolver(*args, **kwargs)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/strawberry_django/resolvers.py", line 83, in sync_resolver
    retval = resolver(*args, **kwargs)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/strawberry/types/fields/resolver.py", line 203, in __call__
    return self.wrapped_func(*args, **kwargs)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/gqlauth/core/mixins.py", line 24, in field
    return cls.resolve_mutation(info, input_type(**kwargs))  # type: ignore
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/gqlauth/user/resolvers.py", line 376, in resolve_mutation
    return ObtainJSONWebTokenType.authenticate(info, input_)
  File "/home/jean/Development/proj/work/mine/AgriSocial/agri2/api/v6/.venv/lib/python3.10/site-packages/gqlauth/jwt/types_.py", line 166, in authenticate
    USER_MODEL.USERNAME_FIELD: getattr(input_, USER_MODEL.USERNAME_FIELD),
AttributeError: 'ObtainJSONWebTokenInput' object has no attribute 'username'
[08/Jul/2024 08:52:20] "POST /users/graphql/ HTTP/1.1" 200 16

**Comment by nrbnlulu** [comment]
your user model should have `USERNAME_FIELD="email"`

**Comment by jbdura** [comment]
SystemCheckError: System check identified some issues:

ERRORS:
users.CustomUser: (auth.E002) The field named as the 'USERNAME_FIELD' for a custom user model must not be included in 'REQUIRED_FIELDS'.
	HINT: The 'USERNAME_FIELD' is currently set to 'email', you should remove 'email' from the 'REQUIRED_FIELDS'.
	
```
# users/models.py

from django.contrib.auth.models import AbstractUser
from django.db import models

from gallery.models import Image


# Create your models here.


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, blank=False, max_length=254, verbose_name="email address")
    profile_image = models.OneToOneField(Image, on_delete=models.SET_NULL, null=True, blank=True,
                                         related_name='user_profile_image')  # Add this line

    USERNAME_FIELD = "email"  # e.g: "username", "email"
    # EMAIL_FIELD = "primary_email"  # e.g: "email", "primary_email"

    def __str__(self):
        return self.email
```

**Comment by jbdura** [comment]
I managed to fix it by doing this
  ```
    USERNAME_FIELD = "email"  # to log in with email
    EMAIL_FIELD = "email"  # e.g: "email", "primary_email"
    REQUIRED_FIELDS = [] # disabled default features
```

```
from gqlauth.settings_type import GqlAuthSettings, email_field

AUTH_USER_MODEL = 'users.CustomUser'


GQL_AUTH = GqlAuthSettings(
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_REQUIRE_CAPTCHA=False,
    JWT_TIME_FORMAT="%Y-%m-%dT%H:%M:%S",  # A valid 'strftime' string for the token payload
    JWT_LONG_RUNNING_REFRESH_TOKEN=True,  # Enable refresh tokens
    JWT_EXPIRATION_DELTA=timedelta(minutes=60),  # Token expiration time, e.g., 30 minutes
    JWT_REFRESH_EXPIRATION_DELTA=timedelta(days=7),
    EXPIRATION_ACTIVATION_TOKEN=timedelta(minutes=60),
    LOGIN_FIELDS={email_field},

)

```
can this be added to documentation for simplicity?

**Comment by nrbnlulu** [comment]
Go for it 😁
