### ISSUE TITLE
JwtSchema doesn't work in testing environment.

### ISSUE THREAD

**Issue by shmoon-kr** [nrbnlulu/strawberry-django-auth#570]
# Prerequisites

* [V] Is it a bug?

# Description

I'm using the gqlauth package in a django channels environment. Recently, while writing test code, I noticed that the JwtSchema in gqlauth.core.middleware is not working properly in my testing environment.

# Steps to Reproduce

Here's an example of where the problem might occur.

schema.py

```
from gqlauth.core.middlewares import JwtSchema

...

test_schema = JwtSchema(query=Query, mutation=Mutation, extensions=extensions)
```

tests.py

```
from schema import schema

class PopupTestCase(TestCase):
    test_popup = None

    def setUp(self):
        self.test_popup = Popup.objects.create()

    @pytest.mark.asyncio
    async def test_popup_query(self) -> None:
        assert self.test_popup is not None

        query = '''
        query MainPage {
          popups {
            id
            launchAt
            expireAt
            content
          }
        }
        '''

        resp = await test_schema.execute(query, variable_values={}, context_value={})
        assert resp.data is not None
        assert len(resp.data['popups']) == 1 and resp.errors is None  # 1 Popup exists

        return
```

result :

```
======================================================================
ERROR: test_popup_query (keewi.tests.test_query.PopupTestCase.test_popup_query)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shmoon/PycharmProjects/keewit_admin/venv/lib/python3.11/site-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shmoon/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/shmoon/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/shmoon/PycharmProjects/keewit_admin/venv/lib/python3.11/site-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shmoon/PycharmProjects/keewit_admin/keewi/tests/test_query.py", line 29, in test_popup_query
    resp = await schema.execute(query, variable_values={}, context_value={})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shmoon/PycharmProjects/keewit_admin/venv/lib/python3.11/site-packages/gqlauth/core/middlewares.py", line 102, in execute
    self._inject_user_and_errors(kwargs)
  File "/home/shmoon/PycharmProjects/keewit_admin/venv/lib/python3.11/site-packages/gqlauth/core/middlewares.py", line 114, in _inject_user_and_errors
    request = context["request"]
              ~~~~~~~^^^^^^^^^^^
KeyError: 'request'
```

----------------------------------------------------------------------

## Expected behavior

Tests are done but they fail actually as described above.

## Etc.

I believe the issue is caused by the part of the JwtSchema that references request - in the testings environment, the request doesn't actually exist, so it seems to be trying to reference it and getting an error.

I found a simple workaround: instead of using JwtSchema in the testings environment, I use strawberry.Schema, and the test itself works fine. However, I am concerned that just because it passes the tests this way, there is no guarantee that it will work in production. If possible, I'd like to see this issue resolved so that JwtSchema works properly in the testing environment as well.

If you need me to, I'd be happy to create code to reproduce this case and post it to the repository, and I might even contribute to this project by modifying the code myself if you provide proper guidance.

--

**Comment by nrbnlulu** [comment]
what is `test_schema`?

**Comment by shmoon-kr** [comment]
test_schema is an instance of the gqlauth.core.middlewares.JwtSchema class that replaces strawberry.Schema. (I made a typo in the original post so it seems to make you confusing.) The official gqlauth documentation suggests using gqlauth.core.middlewares.JwtSchema instead of strawberry.Schema, as shown below.

----

Now in order to have the user inside info.context.request we need to use a custom schema schema.py

from gqlauth.core.middlewares import JwtSchema


arg_schema = JwtSchema(
    query=Query, mutation=Mutation, subscription=Subscription
)

**Comment by shmoon-kr** [comment]
I just created a source code repository that reproduces this case.
Please refer to https://github.com/shmoon-kr/strawberry-test
As you can see in the README.md file, you can reproduce it by simple `python ./manage.py tests` command.

**Comment by nrbnlulu** [comment]
well it is expected that it will fail. You are not supposed to work with the jwt schema itself.
This doesn't work because you don't have a request object in your context which is expected to fail.
You can either do tests via some `TestClient` or conditionally use the jwt schema like so 
```py
def get_schema(auth: bool) -> Schema:
schema_class = JwtSchema if auth else strawberry.schema
return schema_class(
Query,
Mutation
)
```
