### ISSUE TITLE
Support for Django 5.1 and python 3.13

### ISSUE THREAD

**Issue by fanto88** [nrbnlulu/strawberry-django-auth#582]
# Prerequisites
*Feel free to just say what you want and remove this template.*

* [] Is it a bug?
* [X] Is it a new feature?
* [X] Is it a question?
* [ ] Can you reproduce the problem?
* [ ] Are you running the latest version?
* [ ] Did you check for similar issues?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/nrbnlulu/strawberry-django-auth/blob/master/CONTRIBUTING.md) guide.

# Description

There will be support for django 5.1 and python 3.13?
I get this error during `pip install strawberry-django-auth`

Collecting strawberry-django-auth
  Using cached strawberry_django_auth-0.3.7.0-py3-none-any.whl.metadata (5.5 kB)
Collecting Django<4.1,>=3.2 (from strawberry-django-auth)
  Using cached Django-4.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting Pillow<10.0.0,>=9.2.0 (from strawberry-django-auth)
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel  
          return hook(config_settings)
        File "/tmp/pip-build-env-rntlylt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel       
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rntlylt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-rntlylt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-rntlylt_/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 29, in <module>
        File "<string>", line 26, in get_version
      KeyError: '__version__'
      [end of output]

**Comment by nrbnlulu** [comment]
yeah we should add that..

**Comment by nrbnlulu** [comment]
about python 3.13 is it Im not sure I'll add support for it now at least until 3.14 is released since it has no significant value for me. if someone really needs 3.13 he can submit a PR
